title: Esperantskribaĉoj
description: Mi eklernis Esperanton en 2011, kaj foje ekzercis ekde tiam. Ĉi tioj estas miajn pli longa Esperanto skriboj, estis skribitaj kiel mi studis.
theme: jekyll-theme-minimal
defaults:
  -
    scope:
      path: ""
    values:
      author: "Madison Scott-Clary"
