title: Esperantskribaĉoj
description: Mi eklernis Esperanton en 2011, kaj foje ekzercis ekde tiam. Ĉi tiuj estas miaj plej longaj Esperanto-skribaĵoj, ili estis skribitaj kiam mi studis.
theme: jekyll-theme-minimal
defaults:
  -
    scope:
      path: ""
    values:
      author: "Madison Scott-Clary"
